BugTrackerV1/Models/Role.cs
namespace BugTrackerV1.Models
{
    public class Role
    {
        public Role()
        {
            this.UserRoles = new HashSet<UserRoles>();
            this.RolePermissions = new HashSet<RolePermissions>();
        }

        public int Id { get; set; }
        public string NameRole { get; set; }
        public string Description { get; set; }

        public virtual ICollection<UserRoles> UserRoles { get; set; }
        public virtual ICollection<RolePermissions> RolePermissions { get; set; }
    }


}

BugTrackerV1/Controllers/RolesController.cs
using BugTrackerV1.Models.ViewModel.PermissionVM;
using BugTrackerV1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BugTrackerV1.Models.ViewModel.RoleVM;

namespace BugTrackerV1.Controllers
{
    public class RolesController: Controller
    {
        private readonly ApplicationContext _context;

        public RolesController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            var viewModel = new AssignRoleViewModel
            {
                Users = await _context.User.ToListAsync(),
                Roles = await _context.Role.ToListAsync()
            };

            return View(viewModel);
        }

        // POST: Roles/Assign
        [HttpPost]
        public async Task<IActionResult> Assign(AssignRoleViewModel model)
        {
            var userRole = _context.UserRoles.FirstOrDefault(ur => ur.UserId == model.SelectedUserId);
            if (model.SelectedRoleId != 0)
            {
                if (userRole != null)
                {
                    userRole.RoleId = model.SelectedRoleId;
                }
                else
                {
                    _context.UserRoles.Add(new UserRoles { UserId = model.SelectedUserId, RoleId = model.SelectedRoleId });
                }
            }
            else
            {
                if (userRole != null)
                {
                    _context.UserRoles.Remove(userRole);
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View(new Models.ViewModel.RoleVM.CreateRoleViewModel());
        }

        // POST: Roles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Models.ViewModel.RoleVM.CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new Role
                {
                    NameRole = model.NameRole,
                    Description = model.Description
                };

                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
    }
}

BugTrackerV1/Views/Roles/Create.cshtml
@model BugTrackerV1.Models.ViewModel.RoleVM.CreateRoleViewModel;
@{
    ViewData["Title"] = "Создание роли";
    Layout = "_ContentNavbarLayout";
    ViewData["isMenu"] = false;
}

<h2>Создание роли</h2>

<div class="card m-3 p-3">
    <form asp-action="Create">
        <div class="form-group">
            <label asp-for="NameRole" class="control-label">Название</label>
            <input asp-for="NameRole" class="form-control" />
            <span asp-validation-for="NameRole" class="text-danger"></span>
        </div>
        <div class="form-group my-2">
            <label asp-for="Description" class="control-label">Описание</label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>
    </form>
</div>

BugTrackerV1/Views/Roles/Index.cshtml
@model BugTrackerV1.Models.ViewModel.RoleVM.AssignRoleViewModel;
@{
    ViewData["Title"] = "Назначить роль";
    Layout = "_ContentNavbarLayout";
    ViewData["isMenu"] = false;
}
<h2>Назначение роли</h2>

<div class="card m-3 p-3">
    <table class="table">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Роль</th>
                <th>Назначить роль</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.Users)
            {
                <tr>
                    <td>@user.FirstName @user.LastName</td>
                    <td>
                        @if (user.UserRoles.Any(x => x.UserId == user.Id))
                        {
                            @user.UserRoles.FirstOrDefault()?.Role.NameRole
                        }
                    </td>
                    <td>
                        <form method="post" asp-action="Assign">
                            <div class="row">
                                <div class="col">
                                    <input type="hidden" name="SelectedUserId" value="@user.Id" />
                                    <select name="SelectedRoleId" class="form-control">
                                        <option value="0">Отсутствует</option>
                                        @foreach (var role in Model.Roles)
                                        {
                                            <option value="@role.Id">@role.NameRole</option>
                                        }
                                    </select>
                                </div>
                                <div class="col">
                                    <button type="submit" class="btn btn-primary">+</button>
                                </div>
                            </div>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <button onclick="location.href='@Url.Action("Create", "Roles")'" style="width: 170px;" class="btn btn-primary my-2">Создать роль</button>
</div>