BugTrackerV1/Models/ViewModel/BacklogViewModel.cs
namespace BugTrackerV1.Models.ViewModel
{
    public class BacklogViewModel
    {
        public Sprint? ActiveSprint { get; set; }
        public List<Sprint> FutureSprints { get; set; }
        public List<Models.Issue> BacklogTasks { get; set; }
    }
}

BugTrackerV1/Controllers/BacklogController.cs
using BugTrackerV1.Filters;
using BugTrackerV1.Models;
using BugTrackerV1.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BugTrackerV1.Controllers
{
    [Authorize]
    [ServiceFilter(typeof(EnsureProjectSelectedFilter))]
    [Authorize(Policy = "TracVw")]
    public class BacklogController: Controller
    {

        private readonly ApplicationContext _context;

        public BacklogController(ApplicationContext context)
        {
            _context = context;
        }

        
        public IActionResult Index()
        {
            Sprint? activeSprint = null;
            var projectId = int.Parse(User.FindFirst("SelectedProjectId").Value);
            var project = _context.Project.FirstOrDefault(x => x.Id == projectId);
            if (project.Sprint != null)
            {
                activeSprint = project.Sprint;
            }

            var today = DateTime.Today;
            var futureSprints = _context.Sprint
                .Where(sprint => sprint.EndDate >= today && sprint.StartDate >= today && sprint.Project.ActiveSprintId != sprint.Id).ToList();


            var backlogTasks = _context.Issue.Where(t => t.SprintId == null && t.ProjectId == projectId).ToList();

            var viewModel = new BacklogViewModel
            {
                ActiveSprint = activeSprint,
                FutureSprints = futureSprints,
                BacklogTasks = backlogTasks
            };

            return View(viewModel);
        }

        public IActionResult CreateSprint()
        {
            ViewBag.Projects = _context.Project.ToList();
            var model = new SprintViewModel
            {
                StartDate = DateTime.Today.AddDays(1),
                EndDate = DateTime.Today.AddDays(2) 
            };
            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> SetStartSprint(int sprintId) 
        {
            var card = await _context.Sprint.FirstOrDefaultAsync(x => x.Id == sprintId);
            if (card.Project.ActiveSprintId == null)
            {
                card.Project.ActiveSprintId = card.Id;
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> CompleteSprint(int sprintId) 
        {
            var card = await _context.Sprint.FirstOrDefaultAsync(x => x.Id == sprintId);
            if (card.Project.ActiveSprintId != null)
            {
                card.Project.ActiveSprintId = null;
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSprint(SprintViewModel model)
        {
            if (model.StartDate < DateTime.Today.AddDays(1))
            {
                ModelState.AddModelError("StartDate", "Дата начала спринта не может быть ранее завтрашнего дня.");
            }

            if (ModelState.IsValid)
            {
                var sprint = new Sprint
                {
                    NameSprint = model.NameSprint,
                    StartDate = model.StartDate,
                    EndDate = model.EndDate,
                    ProjectId = int.Parse(User.FindFirst("SelectedProjectId").Value)
                };

                _context.Sprint.Add(sprint);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Projects = _context.Project.ToList();
            return View(model);
        }

    }
}

BugTrackerV1/Views/Backlog/CreateSprint.cshtml
@model BugTrackerV1.Models.ViewModel.SprintViewModel
@{
    ViewData["Title"] = "Создание спринта";
}

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var startDateInput = document.querySelector("[name='StartDate']");
            var endDateInput = document.querySelector("[name='EndDate']");

            startDateInput.addEventListener("change", function () {
                var startDate = new Date(startDateInput.value);
                var minEndDate = new Date(startDate);
                minEndDate.setDate(minEndDate.getDate() + 1);
                endDateInput.min = minEndDate.toISOString().split("T")[0];
            });
        });
    </script>
}


<div class="container-fluid">
    <div class="bg-light task-main p-3 rounded-3">
        <h2 class="my-3">@ViewData["Title"]</h2>
        <form asp-action="CreateSprint" method="post" class="form-horizontal">
            <div class="form-group">
                <label asp-for="NameSprint" class="control-label"></label>
                <input asp-for="NameSprint" class="form-control" />
                <span asp-validation-for="NameSprint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

BugTrackerV1/Views/Backlog/Index.cshtml
@{
    ViewData["Title"] = "Бэклог";
}

@section PageScripts {
    <script src="~/js/ui-modals.js"></script>
}
@* ************** Content ************** *@

@model BugTrackerV1.Models.ViewModel.BacklogViewModel

<h4 class="py-3 mb-4">
    <span class="text-muted fw-light">Бэклог /</span> Задачи
</h4>

@if (Model.ActiveSprint != null)
{
    <div class="bg-light task-main p-3 rounded-3">
        <div class="d-flex bd-highlight mb-2">
            <h2 class="me-auto p-2 bd-highlight">Активный спринт: @Model.ActiveSprint.NameSprint (@Model.ActiveSprint.StartDate.ToShortDateString() - @Model.ActiveSprint.EndDate.ToShortDateString())</h2>
            <button class="btn btn-secondary buttonSize" onclick="location.href='@Url.Action("CompleteSprint", new { sprintId = Model.ActiveSprint.Id })'">Завершить</button>
        </div>
        <ul class="list-group">
            @foreach (var task in Model.ActiveSprint.Issue)
            {
                <li class="list-group-item d-flex bd-highlight">
                    <label class="bd-highlight">
                        <a href="@Url.Action("Detail", "Issue", new {issueId = task.Id})">#@task.Id</a>
                    </label>
                    <label class="mx-4 bd-highlight">@task.Title</label>
                    <label class="ms-auto bd-highlight">@task.Status.NameStatus</label>
                </li>
            }
        </ul>
    </div>
}

@foreach (var sprint in Model.FutureSprints)
{
    <div class="bg-light task-main p-3 rounded-3">
        <div class="d-flex bd-highlight mb-2">
            <h2 class="me-auto p-2 bd-highlight">@sprint.NameSprint (@sprint.StartDate.ToShortDateString() - @sprint.EndDate.ToShortDateString())</h2>
            <button class="btn btn-secondary buttonSize" onclick="location.href='@Url.Action("SetStartSprint", new { sprintId = sprint.Id })'">Установить</button>
        </div>
        <ul class="list-group">
            @foreach (var task in sprint.Issue)
            {
                <li class="list-group-item d-flex bd-highlight">
                    <label class="bd-highlight">
                        <a href="@Url.Action("Detail", "Issue", new {issueId = task.Id})">#@task.Id</a>
                    </label>
                    <label class="mx-4 bd-highlight">@task.Title</label>
                    <label class="ms-auto bd-highlight">@task.Status.NameStatus</label>
                </li>
            }
        </ul>
    </div>
}

<div class="my-4 bg-light task-main p-3 rounded-3">
    <div class="d-flex bd-highlight mb-2">
        <h2 class="me-auto p-2 bd-highlight">Бэклог</h2>
        <button class="btn btn-secondary p-2 bd-highlight buttonSize" onclick="location.href='@Url.Action("CreateSprint", "Backlog")'">Создать спринт</button>
    </div>
    <ul class="list-group">
        @foreach (var task in Model.BacklogTasks)
        {
            <li class="list-group-item d-flex bd-highlight">
                <label class="bd-highlight">
                    <a href="@Url.Action("Detail", "Issue", new {issueId = task.Id})">#@task.Id</a>
                </label>
                <label class="mx-4 bd-highlight">@task.Title</label>
                <label class="ms-auto bd-highlight">@task.Status.NameStatus</label>
            </li>
        }
    </ul>
</div>